### ISSUE TITLE
[ issues/issue_99] : Deleting a private channel after its creation 

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#116] opened 2023-08-22 08:19 UTC
### Description du Problème:
1. The channel is deleted before entering the password 
2. When i click on Yes in the dialog box to confirm channel delete => Error 'You cannot enter this channel'
3. When deleted, the window of the deleted channel is still displayed

### Étapes pour Reproduire:
Prequisites: a user has at least one friend
1. Go to channel page
2. Click on Create Channel
4. Fill the form for public channel and protected by password and choose password
5. Create
6. Delete the channel

### Capture d'Écran:

STEP 1 :
![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/ee389c01-cdea-4d38-a195-8b87b25d95d8)

STEP 2 :
![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/281e7ed1-b2a4-474f-85c3-99b8c32fd407)

STEP 3: 
![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/278bbcd6-aec9-42e0-9386-6b8857aa612b)

STEP 4: 
![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/03a3dfb9-a43a-4676-ab2f-0a85cae6def3)

STEP 5: 
![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/9302058e-d8ec-4ad0-9c50-9c6dfa601fd3)

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment] 2023-08-22 13:59
duplicate of issue #122

**Closed by Alicia-bites** 2023-08-22 13:59 UTC
Labels: bug
